### PR TITLE
Update and rename 3-Add two numbers cpp to 3-Add two numbers.cpp

### PR DESCRIPTION
**Pull request by lakshya3841**

### CODE REVIEW

**Comment by lakshya3841** [comment]
please make it hacktober fest- accepted and merge it

**Review by ashwani-rathee — CHANGES_REQUESTED** [review]
Actually this repository is for more younger kids like 14,15......I can add the labels if you do 4 more of these programs :)Congrats on one of your first contributions ever i believe

**Comment by lakshya3841** [comment]
There is another idea ,can you just mention using comments that // There are more ways and we have mentioned 2 of the following ways;

**Comment by ashwani-rathee** [comment]
Ohh definitely!!I could do that,let me make the changes there to tell the different paths possible.

**Comment by lakshya3841** [comment]
I am 14 what u thought lol , participating in hacktober if you want proof you can mail me

**Comment by ashwani-rathee** [comment]
I understand!! pls add 4 more of programs for me to verify that you're not a spammer then I will be able to merge it..as adding two numbers is not enough,select any five and get them done and send the pull request..

**Pull request merged**
